### ISSUE TITLE
Partition values issue

### ISSUE THREAD

**Issue by cccc1999** [FINRAOS/herd#170]
Hi guys,

I am very interested in the Finra Herd project, and want to check it out, but after I followed the tutorial steps, the webapp told me the partition values are not correct, could someone help? 
Also I just want to check out the Herd demo with some sample data, do you have an existing demo that people can play with?

<img width="1437" alt="screenshot 2016-09-13 09 49 45" src="https://cloud.githubusercontent.com/assets/682886/18458868/84370000-7997-11e6-8b9f-2e0c957e4e66.png">

Thanks a lot!

**Comment by nateiam** [comment]
Hello Cheng, nice to meet you. I work at FINRA as the Product Owner of the
team that developed Herd and released it to the OSS community. I’m glad
you’re interested in Herd and took the time to get through the demo install
and tutorial.


Herd was developed as API-first and our primary use case at this time is
programmatic access by technical teams. The page you’re using was part of
our first foray into UI – the error you are seeing is caused by that page
making a [bad] assumption about how data is registered. I can provide a
curl script that adds data to the registrations you created in the quick
start tutorial – but the really good news is that we’re well into the
development of a UI that has much more comprehensive coverage of our
metadata model.

In my experience the best thing for us to do is arrange for a video or
telephone call to learn more about your interest and share more about why
we created Herd and what makes it click. I can also update you on plans for
our UI release and how to best demo Herd and create sample data.

I’m available to talk soon, have some openings mid-day Wed and Thurs and a
lot of Friday afternoon (all time US Eastern). Also free in evenings. Let
me know a few times that work for you and we can talk for 30 minutes or so
and take it from there.

Thanks

- Nate Weisz

**Comment by cccc1999** [comment]
@nateiam thanks so much for the detailed response, I'd love to chat with you and learn more about Herd. We are trying to see if we can use Herd in our project as a metadata/schema management tool. Lets try to talk Mid-day Thursday, can I have your skype username(or your preferred communication tool)?

**Comment by nateiam** [comment]
Looking forward to talking mid-day Thursday. I'm not on Skype much but am
always on Google Hangout chat as nateiam@gmail.com and also you can SMS me
at 3015298330 to make arrangements. Let me know a few times that work and
we can choose the right media to communicate :-)

**Comment by cccc1999** [comment]
added you on google hangout! Looking forward to chat!
