### ISSUE TITLE
Terminating long-running workflow impacted health of system

### ISSUE THREAD

**Issue by nateiam** [FINRAOS/herd#229]
As a Herd Administrator I want to ensure the workflow termination always executes without impacting system health 

Tech Note - this was triggered by a termination operation on a workflow that was stuck in a  loop for an extended period of time. This operation pegged the app server CPU and made the system non-responsive, see details below. Note that the termination operation has run successfully 

Acceptance Criteria:
* Workflow terminate executes successfully on very long-running workflows. 
* Termination occurs without significant impact on server resources

Solution note: workflow had started many child processes in the Activiti engine, some of which were deeply nested. The termination that affected the CPU was calling Activiti delete API on the parent process. The solution was to locate all the child processes and delete from the bottom up.

**Comment by seoj** [comment]
Kudos to the team for finding this one. Must've been one hairy issue to root cause.

**Comment by ShaneEbersole** [comment]
Max!!!!! :-D


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: "Jung (Max) Seo" <notifications@github.com> Date: 12/9/16  10:43 AM  (GMT-05:00) To: FINRAOS/herd <herd@noreply.github.com> Subject: Re: [FINRAOS/herd] Terminating long-running workflow impacted health of system (#229) 
Kudos to the team for finding this one. Must've been one hairy issue to root cause.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FINRAOS/herd","title":"FINRAOS/herd","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FINRAOS/herd"}},"updates":{"snippets":[{"icon":"PERSON","message":"@seoj in #229: Kudos to the team for finding this one. Must've been one hairy issue to root cause. "}],"action":{"name":"View Issue","url":"https://github.com/FINRAOS/herd/issues/229#issuecomment-266044890"}}}

**Comment by nateiam** [comment]
It was fun times, @mchao47 could tell you all about how it "impacted health of [the] system" and @afelde and @DavidBalash about the troubleshooting. Getting into the Activiti source code - fun. 

Good hearing from you @seoj, we miss you!

**Comment by seoj** [comment]
happy holidays ya'll
good tidings from cali
