### ISSUE TITLE
UI - 403

### ISSUE THREAD

**Issue by namebrandon** [FINRAOS/herd#360]
v 58.0, extracted jar file and submitted herd.localdb.template as CF template. Standard defaults, except changed m1.large to m3.large, and chose my own PEM file. 

us-east-1

HerdRestAPI and HerdBuildInfo URL's work appropriately, but UI fails to load with 403.

http://34.229.x.x:8080/herd-app/herd-ui/

```
HTTP Status 403 – Forbidden
Type Status Report

Description The server understood the request but refuses to authorize it.

Apache Tomcat/8.5.23


```

**Comment by manasguduri** [comment]
Hello Brandon,

I am having the same issue, did you get a solution to this issue?

Thanks,
Manas

**Comment by tinshuksingh** [comment]
Hello Manas,

We faced the same issue. We analysed herd code and the sql files from _herd-db-scripts.jar_ and came to know that '**FN_DISPLAY_HERD_UI**' entry was missing from the table '**scrty_fn_lk**'.
We executed below query which fixed the issue.
`INSERT INTO scrty_fn_lk VALUES('FN_DISPLAY_HERD_UI', current_timestamp, 'SYSTEM', current_timestamp, 'SYSTEM');`

**Comment by manasguduri** [comment]
Hello Tinshuksingh,

Thank you very much for your response. I will follow that and will let you know !

Manas

**Comment by manasguduri** [comment]
Hello Tinshuksingh,

I have added the line in the 'FN_DISPLAY_HERD_UI' as you suggested, and now I get a blank page other than that 403 Error.

I even tried restarting tomcat and Postgresql, but no result.

Is there anything, I have to do !

Thanks,
Manas

**Comment by tinshuksingh** [comment]
Hi Manas,

Herd-ui code is not available in `https://github.com/FINRAOS/herd` repository. Few days back they created a new repository `https://github.com/FINRAOS/herd-ui`. Here you will find the latest herd-ui code. With some configuration changes you can associate Herd-UI to your Herd instance.

**Comment by nateiam** [comment]
Hi @manasguduri @tinshuksingh @namebrandon 

First off, sorry to leave this ticket hanging. We're getting more people involved in supporting Herd in GitHub!

Next, I am absolutely charged up to see people getting into the code such as this crowd has done. Let the open source activity begin! And you all dug in the right direction to the function mapping table. 

The only think you couldn't have known is that we removed the security function mapping as we deprecated the old UI - it was super-minimal and we've been hard at work on the new Herd-UI which is comprehensive and (we think) awesome. But when we deprecated the old UI we left the output link in the CloudFormation template which caused some confusion. 

So, as Manas said we have released [Herd-UI](https://github.com/FINRAOS/herd-ui) along with a configuration/test guide and user guide in the [Herd-UI wiki](https://github.com/FINRAOS/herd-ui/wiki).

And we are hard at work on a new CloudFormation template that builds a stack including Herd and Herd-UI. And we'll include the corrected UI link at that time :-)

Thanks all and we'll keep on top of issues and I know you all will have an eye out for new releases!

**Comment by manasguduri** [comment]
Hello @nateiam, Thank you for your response. I have few questions regarding the Herd Data Catalog.

1. As you mentioned Herd is Open-source, Is there any process that I can install it on my system remotely? 
2. Is there any other process of installing Herd on an EC2 Server other than cloud formation template?
3. We are looking for an open-source Data Catalog for our personal company use, will the open-source version able to handle large amount of data like 5GB of incoming data a day?
4. Where can I find the features of Herd Data Catalog? 

Waiting for your response.

Thanks,
Manas

**Comment by manasguduri** [comment]
@tinshuksingh 
Hello Tinshuk, you mentioned the link for the Herd-UI code, and what are the configuration changes should be made? can you please give me more information regarding that?

Thanks,
Manas

**Comment by nateiam** [comment]
@tinshuksingh there is a  [Config Guide](https://github.com/FINRAOS/herd-ui/wiki/Configuration-and-Test-Guide) and also check out the User Guide on the same Herd-UI wiki!

**Comment by nateiam** [comment]
@manasguduri great to see your interest! Answers below. 

And any additional background you can provide will also be helpful. Knowing roughly what you are trying to do could allow me to answer better. Feel free to write to herd@finra.org if you want to share more information.

> As you mentioned Herd is Open-source, Is there any process that I can install it on my system remotely?

Not sure I understand this question fully - but I hope it is covered in some of the answers below.

> Is there any other process of installing Herd on an EC2 Server other than cloud formation template?

The cloud formation gives you a one-click demo install of Herd and also can serve as a reference if you want to perform the install differently. I supposed you would install the herd .war on any EC2 with Tomcat and install PostgresSQL or another DB as well and do all the configurations manually or write your own automation

We are looking for an open-source Data Catalog for our personal company use, will the open-source version able to handle large amount of data like 5GB of incoming data a day?

Yes, we have the open source version installed at FINRA and regularly process TBs in a day. Actually Herd is not so sensitive to the physical size of the data since the data is placed directly in S3. Herd does care about how many objects are registered in the Herd catalog. But we also regularly handle tens of thousands of objects and data partitions in a day. It's worth noting that we have this deployed in a pretty robust fashion with load balancing across multiple EC2s, etc. 

But even without fully analyzing your data characteristics, that would probably be okay if you are willing to deploy to a robust environment.

> Where can I find the features of Herd Data Catalog?

The best overviews are the [What is Herd](https://github.com/FINRAOS/herd/wiki/what-is-herd) on the Herd wiki and the [API documentation](http://finraos.github.io/herd/docs/0.1.0/rest/index.html). The wiki also has some additional information and if you want more background or details, let us know via herd@finra.org and we can talk.

> I am in a confusion, Is the Herd app working right now? or When Can I expect the working Herd app, that you mentioned will be released soon?

I think you are referring to the Herd-UI which was just released at https://github.com/FINRAOS/herd-ui, I think you will like it!
